/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    BittMixx: {
      address:
        "0xfc0c6962d6a7c0143212e07b566030107844ac8189e74a62f46cc15314fed2",
      abi: [
        {
          type: "impl",
          name: "BittmixxImpl",
          interface_name: "contracts::bittmixx::IBittMixx",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::bittmixx::IBittMixx",
          items: [
            {
              type: "function",
              name: "deposit",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
                {
                  name: "commitment",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "withdraw",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "hasher",
              inputs: [
                {
                  name: "value",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bittmixx::BittMixx::StrkDeposited",
          kind: "struct",
          members: [
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "commitment",
              type: "core::felt252",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bittmixx::BittMixx::StrkWithdrawn",
          kind: "struct",
          members: [
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "amount_left",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bittmixx::BittMixx::Event",
          kind: "enum",
          variants: [
            {
              name: "StrkDeposited",
              type: "contracts::bittmixx::BittMixx::StrkDeposited",
              kind: "nested",
            },
            {
              name: "StrkWithdrawn",
              type: "contracts::bittmixx::BittMixx::StrkWithdrawn",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x5129fb52cce7b5aad3e8fdf0efaab50732cc02b3417e4dcfaa7af0396204a73",
    },
  },
} as const;

export default deployedContracts;
