/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    UltraStarknetZKHonkVerifier: {
      address:
        "0xf5fae7cdb76ac28b83b87ab05ff4debe3682b73751c7b681ab175fe399e161",
      abi: [
        {
          type: "impl",
          name: "IUltraStarknetZKHonkVerifier",
          interface_name:
            "contracts::honk_verifier::IUltraStarknetZKHonkVerifier",
        },
        {
          type: "struct",
          name: "core::array::Span::<core::felt252>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::felt252>",
            },
          ],
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::integer::u256>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::integer::u256>",
            },
          ],
        },
        {
          type: "enum",
          name: "core::option::Option::<core::array::Span::<core::integer::u256>>",
          variants: [
            {
              name: "Some",
              type: "core::array::Span::<core::integer::u256>",
            },
            {
              name: "None",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::honk_verifier::IUltraStarknetZKHonkVerifier",
          items: [
            {
              type: "function",
              name: "verify_ultra_starknet_zk_honk_proof",
              inputs: [
                {
                  name: "full_proof_with_hints",
                  type: "core::array::Span::<core::felt252>",
                },
              ],
              outputs: [
                {
                  type: "core::option::Option::<core::array::Span::<core::integer::u256>>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::honk_verifier::UltraStarknetZKHonkVerifier::Event",
          kind: "enum",
          variants: [],
        },
      ],
      classHash:
        "0xd259678c52b351856d2209876d6ff899ada388cc72ff2e54e7bafd807edd2d",
    },
    BittMixx: {
      address:
        "0x6aac6f3f70ae7a6a04a5a78088df354489014e4bbb87be5e1308e3eeb63ef32",
      abi: [
        {
          type: "impl",
          name: "BittmixxImpl",
          interface_name: "contracts::bittmixx::IBittMixx",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::felt252>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::felt252>",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::bittmixx::IBittMixx",
          items: [
            {
              type: "function",
              name: "deposit",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
                {
                  name: "commitment",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "withdraw",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
                {
                  name: "nullifier_hash",
                  type: "core::felt252",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "proof",
                  type: "core::array::Span::<core::felt252>",
                },
                {
                  name: "root_hash",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "verifier_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bittmixx::BittMixx::StrkDeposited",
          kind: "struct",
          members: [
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "commitment",
              type: "core::felt252",
              kind: "key",
            },
            {
              name: "leaf_index",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "time",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bittmixx::BittMixx::StrkWithdrawn",
          kind: "struct",
          members: [
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "amount_left",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bittmixx::BittMixx::Event",
          kind: "enum",
          variants: [
            {
              name: "StrkDeposited",
              type: "contracts::bittmixx::BittMixx::StrkDeposited",
              kind: "nested",
            },
            {
              name: "StrkWithdrawn",
              type: "contracts::bittmixx::BittMixx::StrkWithdrawn",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x2ed23472b1f7104e5a5df9edd5139b5a3b8fe594418cbfd7dc8d98bc696918",
    },
  },
} as const;

export default deployedContracts;
