[package]
name = "contracts"
version = "0.2.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.12.0"
openzeppelin_access = ">=2.0.0"
openzeppelin_token = ">=2.0.0"
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v0.18.1" }

[cairo]
sierra-replace-ids = false
inlining-strategy = 2

[dev-dependencies]
openzeppelin_utils = ">=2.0.0"
openzeppelin_testing = ">=4.6.0"
snforge_std = ">=0.49.0"

[[target.starknet-contract]]
casm = true # taggle this to `false` to speed up compilation/script tests
casm-add-pythonic-hints = true

[tool.scarb]
allow-prebuilt-plugins = [
	"snforge_std",
] # Avoids the need to install Rust for snforge_std/starknet-foundry

[tool.fmt]
sort-module-level-items = true

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_9"
block_id.tag = "latest"

[tool]
panic-backtrace = true

